# Turns a natural-language question into a validated, read-only Snowflake query via Cortex.
# Co-authored with CoCo
"""
Natural language to SQL.

:func:`generate_query_plan` asks Cortex for a JSON object containing the SQL
*and* the chart the model thinks fits its own result shape. Asking for the chart
in the same call is more reliable than guessing it afterwards, because the model
knows what its query returns.

The safety gate lives in :mod:`app.sql_guard` and is re-exported here, so
``from app.nl2sql import is_safe_sql`` keeps working. Nothing generated by a
language model reaches Snowflake without passing it - not from the chat tab, and
not from any dashboard widget.
"""

from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path
from typing import Any

from app.error_hints import build_hints, format_attempt_history
from app.metadata_rag import format_tables_for_prompt, load_metadata
from app.snowflake_utils import SQL_MODEL, cortex_complete, summarize_error
from app.sql_guard import check_sql, is_safe_sql  # re-exported for callers

PROMPT_DIR = Path(__file__).parent / "prompts"

#: Chart types the app knows how to render.
VALID_CHART_TYPES = ("kpi", "bar", "hbar", "line", "area", "scatter", "pie", "donut", "table")

#: Sentinel answers the prompt tells the model to return instead of writing a
#: destructive or unanswerable query. Detecting them lets the UI show a proper
#: refusal rather than a row containing a sentence, and means a write request is
#: turned away at the prompt layer as well as by the guard in :mod:`app.sql_guard`.
READ_ONLY_SENTINEL = "this assistant can only read your data"
UNANSWERABLE_SENTINEL = "cannot answer with the available tables"


def sentinel_kind(sql: str) -> str | None:
    """Return ``"read_only"``, ``"unanswerable"`` or None for a generated query.

    Args:
        sql: The generated statement.

    Returns:
        Which deflection the model chose, if any.
    """
    lowered = (sql or "").lower()
    if READ_ONLY_SENTINEL in lowered:
        return "read_only"
    if UNANSWERABLE_SENTINEL in lowered:
        return "unanswerable"
    return None


# ---------------------------------------------------------------------------
# Prompt building and generation
# ---------------------------------------------------------------------------


def load_prompt(name: str) -> str:
    """Read a prompt template from ``app/prompts``."""
    return (PROMPT_DIR / name).read_text(encoding="utf-8")


def build_sql_prompt(question: str, tables: list[dict[str, Any]]) -> str:
    """Fill the SQL system prompt with only the retrieved table metadata."""
    meta = load_metadata()
    template = load_prompt("sql_system_prompt.txt")
    return (
        template.replace("{schema_block}", format_tables_for_prompt(tables))
        .replace("{today}", date.today().isoformat())
        .replace("{date_range}", meta.get("date_range", "2026"))
        .replace("{question}", question)
    )


def extract_json(reply: str) -> dict[str, Any]:
    """Pull the first JSON object out of a model reply.

    Small models sometimes wrap JSON in markdown fences or add a sentence before
    it, so we locate the outermost balanced ``{...}`` rather than trusting the
    whole reply to be valid JSON.

    Parsing uses ``strict=False`` because models routinely pretty-print SQL with
    real newlines inside the JSON string value, which strict JSON forbids.
    """
    text = reply.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z]*\s*", "", text)
        text = re.sub(r"\s*```$", "", text.strip())

    try:
        return json.loads(text, strict=False)
    except json.JSONDecodeError:
        pass

    start = text.find("{")
    if start == -1:
        raise ValueError("Model reply contained no JSON object.")

    depth = 0
    in_string = False
    escaped = False
    for idx in range(start, len(text)):
        ch = text[idx]
        if in_string:
            if escaped:
                escaped = False
            elif ch == "\\":
                escaped = True
            elif ch == '"':
                in_string = False
            continue
        if ch == '"':
            in_string = True
        elif ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return json.loads(text[start : idx + 1], strict=False)
    raise ValueError("Model reply contained an unterminated JSON object.")


def _clean_sql(sql: str) -> str:
    """Normalise a generated statement: strip fences, trailing semicolons, blanks."""
    text = (sql or "").strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z]*\s*", "", text)
        text = re.sub(r"\s*```$", "", text.strip())
    text = re.sub(r"\s+", " ", text).strip()
    return text.rstrip(";").strip()


def _clean_column(value: Any) -> str | None:
    """Normalise an x/y column hint from the model, mapping junk to None."""
    if value is None:
        return None
    text = str(value).strip()
    if not text or text.lower() in ("null", "none", "n/a", ""):
        return None
    return text


def _plan_from_payload(
    payload: dict[str, Any],
    tables: list[dict[str, Any]],
    *,
    repaired: bool = False,
) -> dict[str, Any]:
    """Convert a raw model payload into a validated query plan.

    Raises:
        ValueError: If the SQL fails :func:`check_sql`.
    """
    sql = _clean_sql(payload.get("sql", ""))
    ok, reason = check_sql(sql)
    if not ok:
        raise ValueError(reason)

    chart_type = str(payload.get("chart_type", "table")).strip().lower()
    if chart_type not in VALID_CHART_TYPES:
        chart_type = "table"

    return {
        "sql": sql,
        "chart_type": chart_type,
        "x": _clean_column(payload.get("x")),
        "y": _clean_column(payload.get("y")),
        "reason": str(payload.get("reason", "")).strip(),
        "tables": [t["name"] for t in tables],
        "repaired": repaired,
    }


def generate_query_plan(question: str, tables: list[dict[str, Any]]) -> dict[str, Any]:
    """Ask Cortex for SQL plus a chart choice, and validate the result.

    Args:
        question: The user's natural-language question.
        tables: Table metadata dicts from
            :func:`app.metadata_rag.retrieve_relevant_tables`.

    Returns:
        A dict with keys ``sql``, ``chart_type``, ``x``, ``y``, ``reason`` and
        ``tables`` (the names that were retrieved).

    Raises:
        ValueError: If the model's reply cannot be parsed, or if the SQL it
            produced fails :func:`check_sql`.
    """
    prompt = build_sql_prompt(question, tables)
    reply = cortex_complete(prompt, model=SQL_MODEL)

    try:
        payload = extract_json(reply)
    except (ValueError, json.JSONDecodeError) as exc:
        raise ValueError(f"Could not read the model's response as JSON: {exc}") from exc

    return _plan_from_payload(payload, tables)


def generate_sql(question: str, tables: list[dict[str, Any]]) -> str:
    """Return just the SQL for ``question`` (thin wrapper over the query plan)."""
    return generate_query_plan(question, tables)["sql"]


def repair_query_plan(
    question: str,
    tables: list[dict[str, Any]],
    attempts: list[dict[str, str]],
) -> dict[str, Any]:
    """Ask Cortex to fix SQL that Snowflake rejected, and re-validate the result.

    Two things make this materially more effective than a blind retry:

    * The full history of failed attempts is included, so the model does not
      propose something it has already been told does not work.
    * :func:`app.error_hints.build_hints` turns the error into a schema-aware
      instruction ("fee does not exist on FEE_SCHEDULE; it exists on
      TRANSACTIONS; FEE_SCHEDULE has these columns: ..."). A generic "fix it"
      leaves the model guessing at the same wrong column repeatedly.

    Args:
        question: The original natural-language question.
        tables: The same table metadata used for the first attempt.
        attempts: Every previous attempt, oldest first, each a dict with ``sql``
            and ``error``. Must not be empty.

    Returns:
        A query plan dict in the same shape as :func:`generate_query_plan`, with
        ``repaired`` set to True.

    Raises:
        ValueError: If the retry is unparseable or fails the safety guard.
    """
    if not attempts:
        raise ValueError("repair_query_plan needs at least one failed attempt.")

    latest = attempts[-1]
    all_tables = load_metadata()["tables"]

    prompt = (
        load_prompt("sql_repair_prompt.txt")
        .replace("{schema_block}", format_tables_for_prompt(tables))
        .replace("{question}", question)
        .replace("{attempt_history}", format_attempt_history(attempts))
        .replace("{error}", latest["error"])
        .replace(
            "{hints}",
            build_hints(latest["error"], tables, all_tables)
            or "(no specific diagnosis - re-read the column lists above)",
        )
    )

    reply = cortex_complete(prompt, model=SQL_MODEL)
    try:
        payload = extract_json(reply)
    except (ValueError, json.JSONDecodeError) as exc:
        raise ValueError(f"Repair attempt was not valid JSON: {exc}") from exc

    return _plan_from_payload(payload, tables, repaired=True)


__all__ = [
    "VALID_CHART_TYPES",
    "build_sql_prompt",
    "check_sql",
    "extract_json",
    "generate_query_plan",
    "generate_sql",
    "is_safe_sql",
    "repair_query_plan",
    "load_prompt",
]
